name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - docker
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t arnaudcayrol/immich-selfie-timelapse:latest
      - name: push image to docker hub
        run: |
          docker login -u arnaudcayrol -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push arnaudcayrol/immich-selfie-timelapse:latest
